import { NextResponse } from 'next/server';
import { generateWithGemini } from '@/lib/gemini-client';
import { db } from '@/config/db';
import { coursesTable, usersTable } from '@/config/schema';
import axios from 'axios';

export const dynamic = 'force-dynamic';

const PROMPT = `Generate Learning Course depends on following details. In which make sure to add Course Name, Description, Course Banner Image Prompt (Create a modern, flat-style 2D digital illustration representing user Topic. Include UI/UX elements such as mockup screens, text blocks, icons, buttons, and creative workspace tools. Add symbolic elements related to user Course, like sticky notes, design components, and visual aids. Use a vibrant, cool palette (blues, purples, oranges) with a clean, professional look. The illustration should feel creative, tech-savvy, and educational, ideal for visualizing concepts in user Course) for Course Banner in 3d format, Chapter Name, Topic under each chapter, Duration for each chapter etc, in JSON format only.

Schema:
{
"course": {
"name": "string",
"description": "string",
"category": "string",
"level": "string",
"includeVideo": "boolean",
"noOfChapters": "number",
"bannerImagePrompt": "string",
"chapters": [
{
"chapterName": "string",
"duration": "string",
"topics": [
"string"
]
}
]
}
}
, User Input:`;

const DEMO_USER_EMAIL = "demo@edu-pilot.app";
const DEMO_USER_NAME = "Demo User";

export async function POST(req) {
    console.log("--- Running UPDATED generate_course-layout API ---");

    const hasGeminiKey = process.env.GEMINI_API_KEY_1 || process.env.GEMINI_API_KEY_2 || process.env.GEMINI_API_KEY_3 || process.env.GEMINI_API_KEY;
    if (!hasGeminiKey) {
        console.error("Missing Gemini API keys in environment.");
        return NextResponse.json({ error: 'Server is not configured correctly. Missing Gemini API Key.' }, { status: 500 });
    }

    try {
        const { courseId, ...formData } = await req.json();

        // Safe upsert of static demo user to satisfy foreign key requirement
        await db.insert(usersTable).values({
            name: DEMO_USER_NAME,
            email: DEMO_USER_EMAIL,
            subscriptionId: "default-subscription"
        }).onConflictDoNothing();

        const aiResponse = await generateWithGemini(PROMPT + JSON.stringify(formData));

        console.log(`✅ Layout successfully generated by: ${aiResponse.source}`);

        const rawJson = aiResponse.text.replace(/```json/g, '').replace(/```/g, '').trim();

        let parsedLayout;
        try {
            parsedLayout = JSON.parse(rawJson);
        } catch (error) {
            console.error("Failed to parse AI response as JSON:", rawJson);
            throw new Error("AI returned invalid JSON format.");
        }

        const ImagePrompt = parsedLayout.course?.bannerImagePrompt;
        const bannerImageUrl = await GenerateImage(ImagePrompt);

        await db.insert(coursesTable).values({
            ...formData,
            courseJson: parsedLayout,
            userEmail: DEMO_USER_EMAIL,
            cid: courseId,
            bannerImageUrl: bannerImageUrl || ''
        }).returning({ id: coursesTable.id });

        return NextResponse.json({ courseId: courseId });

    } catch (error) {
        console.error("API Error in generate_course-layout:", error.message || error);
        return new NextResponse(`Failed to generate course layout: ${error.message || 'Server Error'}`, { status: 500 });
    }
}

const GenerateImage = async (imagePrompt) => {
    if (!imagePrompt || !process.env.AI_GURU_LAB_API_KEY) {
        console.warn("[AI Guru Lab] Skipping image generation: Missing banner image prompt or AI_GURU_LAB_API_KEY.");
        return '/default_image.jpg';
    }

    try {
        console.log("[AI Guru Lab] Generating banner image with AI Guru Lab...");
        const BASE_URL = 'https://aigurulab.tech';
        const result = await axios.post(BASE_URL + '/api/generate-image',
            {
                width: 1024,
                height: 1024,
                input: imagePrompt,
                model: 'flux',
                aspectRatio: "16:9"
            },
            {
                headers: {
                    'x-api-key': process.env.AI_GURU_LAB_API_KEY,
                    'Content-Type': 'application/json',
                },
                timeout: 15000
            });

        if (result?.data?.image) {
            console.log("✅ [AI Guru Lab] Image generation successful.");
            return result.data.image;
        }

        console.warn("[AI Guru Lab] No image returned in response data. Falling back to default banner.");
        return '/default_image.jpg';
    } catch (error) {
        console.error("❌ [AI Guru Lab] Image generation failed:", error?.response?.data || error?.message || error);
        return '/default_image.jpg';
    }
};

