import React, { useState } from 'react';
import Image from 'next/image';
import { Book, LoaderCircle, PlayCircle, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import axios from 'axios';
import { toast } from 'sonner';

function CourseCard({ course }) {
    const [loading, setLoading] = useState(false);

    const onEnrollCourse = async () => {
        setLoading(true);
        try {
            const response = await axios.post('/api/enroll-course', {
                courseId: course.cid
            });

            if (response.data.resp === 'Already Enrolled') {
                toast.warning('You are already enrolled in this course.');
            } else if (response.status === 201) {
                toast.success('Enrolled Successfully!');
            }
        } catch (error) {
            console.error("Enrollment error:", error);
            toast.error("An error occurred during enrollment.");
        } finally {
            setLoading(false);
        }
    };

    // This is a more reliable check to see if content was generated by the AI.
    const hasGeneratedContent = course?.courseJson?.course?.chapters?.length > 0;

    return (
        <div className='shadow rounded-xl flex flex-col'>
            <Image
                src={course?.bannerImageUrl || '/default_image.jpg'}
                alt={course?.name}
                width={400}
                height={300}
                className='w-full aspect-video rounded-t-xl object-cover'
            />
            <div className='p-3 flex flex-col gap-3 flex-grow'>
                <h2 className='font-bold text-lg'>{course?.name}</h2>
                <p className='line-clamp-3 text-gray-400 text-sm flex-grow'>{course?.description}</p>
                <div className='flex justify-between items-center'>
                    <h2 className='flex items-center text-sm gap-2'>
                        <Book className='text-primary h-5 w-5' /> {course?.noOfChapters || 0} Chapters
                    </h2>

                    {/* Use the new, more reliable check here */}
                    {hasGeneratedContent ? (
                        <Button size={'sm'} onClick={onEnrollCourse} disabled={loading}>
                            {loading ? <LoaderCircle className='animate-spin' /> : <PlayCircle />} Enroll Course
                        </Button>
                    ) : (
                        <Link href={'/workspace/edit-course/' + course?.cid}>
                            <Button size={'sm'} variant='outline'>
                                <Settings className="mr-2 h-4 w-4" /> Generate Content
                            </Button>
                        </Link>
                    )}
                </div>
            </div>
        </div>
    );
}

export default CourseCard;