import { NextResponse } from 'next/server';
import { generateWithGemini } from '@/lib/gemini-client';
import axios from 'axios';
import { coursesTable } from '@/config/schema';
import { db } from '@/config/db';
import { eq } from 'drizzle-orm';

export const dynamic = 'force-dynamic';

// Your prompt remains the same
const PROMPT = `Given a chapter name and its topics, generate good length educational HTML content for each topic. Return a JSON with this structure:

{
  chapterName: "<Chapter Name>",
  topics: [
    {
      topic: "<Topic Name>",
      content: "<Generated HTML content>"
    }
  ]
}

User input:`;

export async function POST(req) {
    const hasGeminiKey = process.env.GEMINI_API_KEY_1 || process.env.GEMINI_API_KEY_2 || process.env.GEMINI_API_KEY_3 || process.env.GEMINI_API_KEY;
    if (!hasGeminiKey) {
        console.error("Missing Gemini API keys in environment.");
        return NextResponse.json({ error: 'Server is not configured correctly. Missing Gemini API Key.' }, { status: 500 });
    }

    try {
        const body = await req.json();
        const { course, courseTitle, courseId } = body;

        if (!course?.chapters || !Array.isArray(course.chapters)) {
            return NextResponse.json({ error: 'Invalid or missing course chapters' }, { status: 400 });
        }
        if (!courseId || typeof courseId !== 'string') {
            return NextResponse.json({ error: 'Invalid or missing courseId' }, { status: 400 });
        }

        const promises = course.chapters.map(async (chapter) => {
            try {
                const promptForChapter = PROMPT + JSON.stringify(chapter);

                const aiResponse = await generateWithGemini(promptForChapter);

                console.log(`Chapter "${chapter.chapterName}" generated by ${aiResponse.source}`);
                const rawText = aiResponse.text;

                if (!rawText) throw new Error('Empty response from AI models');

                // The logic for cleaning and parsing the response remains the same
                const rawJson = rawText
                    .replace(/```json/g, '')
                    .replace(/```/g, '')
                    .replace(/[\u0000-\u001F]+/g, '')
                    .trim();

                let parsed;
                try {
                    parsed = JSON.parse(rawJson);
                } catch (error) {
                    console.error("Failed to parse AI response as JSON:", rawJson);
                    // Throw an error so the chapter's catch block can handle it
                    throw new Error("AI returned invalid JSON format.");
                }
                const youtubeData = await GetYoutubeVideo(chapter?.chapterName);

                return {
                    youtubeVideo: youtubeData,
                    courseData: parsed,
                };
            } catch (error) {
                console.error(`Error processing chapter "${chapter.chapterName}":`, error.message);
                return {
                    chapterName: chapter.chapterName,
                    error: `Failed to generate content: ${error.message}`,
                };
            }
        });

        const CourseContent = await Promise.all(promises);

        await db
            .update(coursesTable)
            .set({ courseContent: CourseContent })
            .where(eq(coursesTable.cid, courseId));

        return NextResponse.json({
            courseName: courseTitle,
            courseId,
            CourseContent,
        });
    } catch (error) {
        console.error('API Error:', error);
        return NextResponse.json(
            { error: 'Internal server error', details: error.message },
            { status: 500 }
        );
    }
}

const YOUTUBE_BASE_URL = 'https://www.googleapis.com/youtube/v3/search';

const GetYoutubeVideo = async (topic) => {
    try {
        const params = {
            part: 'snippet',
            q: `${topic} tutorial`,
            maxResults: 4,
            type: 'video',
            key: process.env.YOUTUBE_API_KEY,
        };

        const resp = await axios.get(YOUTUBE_BASE_URL, { params });

        const youtubeVideoList = resp.data.items.map((item) => ({
            videoId: item.id.videoId,
            title: item.snippet.title,
            thumbnail: item.snippet.thumbnails.medium.url,
        }));

        return youtubeVideoList;
    } catch (error) {
        console.error('Error fetching YouTube videos:', error?.message);
        return [];
    }
};